### ISSUE TITLE
Positions of FIPPS clovers

### ISSUE THREAD

**Issue by r3dunlop** [UoG-Nuclear-Physics-Group/ILLData#8]
I don't believe that the FIPPS positions are correct. It would be worthwhile to fix these for 180 summing corrections, complicated addback, angular correlations, suppression, etc.

**Comment by VinzenzBildstein** [comment]
I'm pretty sure that these were simply copied from GRIFFIN, so yes, they are not going to be right.

**Comment by K-Raymond** [comment]
This will be something I will be looking at soon. I'm currently working on getting more detector classes (which should be backwards compatible with most experiments done with FIPPS), here: [ILLData/wip/detectors](https://github.com/K-Raymond/ILLData/tree/wip/detectors)
 
For reference sake, below are some diagrams showing the full array structure. The first picture shows the basic corona ring of HPGe clovers.
![CloverLabeling_FIPPS_v2](https://user-images.githubusercontent.com/11068247/61491064-3b1b1d80-a963-11e9-974a-39940aa7ec01.png)
The second diagram shows the upstream and downstream lampshades used on some experiments. The IFIN clovers have BGO shields. As such I've changed the TFipps class in my repo to TSuppressed.
![CloverLabeling_ViewFromCasemateEntrance_b](https://user-images.githubusercontent.com/11068247/61491065-3b1b1d80-a963-11e9-97bc-aeb07275e7cd.png)

I've been writing my Mnumonics in .cal files as,
**Detector Number from diagram** + 1 = **Detector number in library**

Clover Colours:
0->Blue
1->Green
2->Red
3->White
